---
title: "Resultados Saber Pro"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(UnalData)
library(UnalR)
library(UnalData)     # 0.0.0.9000
library(tidyverse)    # 1.3.1
library(dplyr)        # 1.0.7
library(tidyr)        # 1.1.4
library(highcharter)  # 0.8.2
library(plotly)       # 4.10.0
#library(echarts4r)    # 0.4.2
library(DT)           # 0.19
library(pals)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
source("Funciones.R", encoding = 'UTF-8')
```

Evolución histórica
=======================================================================

Row
-----------------------------------------------------------------------

### Serie

```{r}
Saber <- UnalData::SaberPro %>%
  select(YEAR, SEDE_NOMBRE_ADM, PUNTAJE_GLOBAL, PUNT_RAZO_CUANT, PUNT_INGLES, PUNT_LECT_CRIT, PUNT_COMP_CIUD, PUNT_COMU_ESCR) %>% 
  mutate(SEDE_NOMBRE_ADM = factor(SEDE_NOMBRE_ADM))

Msj <- "Nota: <i>no se incluye los datos atípicos</i>"
Plot_Boxplot(datos       = Saber,
             variable    = PUNTAJE_GLOBAL,
             grupo1      = YEAR,
             outliers    = FALSE,
             jitter      = "QUE",
             violin      = 12345,
             ylim        = c(0, 300),
             colores     = pals::jet(5),
             sizeOutlier = 1,
             colOutlier  = "#FF3366",
             textBox     = "Score",
             titulo      = "Evolución Puntaje Promedio Pruebas Genéricas Examen Saber Pro",
             labelY      = "Puntaje",
             libreria    = "highcharter",
             estilo      = list(hc.Tema = 1, hc.Credits = Msj)
             )
```

Sexo
=======================================================================

Row 
-----------------------------------------------------------------------

### Serie

```{r}
Saber <- UnalData::SaberPro %>%
  select(YEAR, SEXO, PUNTAJE_GLOBAL, PUNT_RAZO_CUANT, PUNT_INGLES, PUNT_LECT_CRIT, PUNT_COMP_CIUD, PUNT_COMU_ESCR) 

Msj <- "Nota: <i>no se incluyen datos atípicos</i>"
Plot_Boxplot(datos       = Saber,
             variable    = PUNTAJE_GLOBAL,
             grupo1      = YEAR,
             grupo2      = SEXO,
             outliers    = FALSE,
             jitter      = "QUE",
             violin      = 12345,
             ylim        = c(0, 300),
             colores     = pals::jet(2),
             sizeOutlier = 1,
             colOutlier  = "#FF3366",
             textBox     = "Score",
             titulo      = "Evolución Puntaje Promedio Pruebas Genéricas Examen Saber Pro por Sexo",
             labelY      = "Puntaje",
             libreria    = "highcharter",
             estilo      = list(hc.Tema = 1, hc.Credits = Msj)
             )
```
Column
-----------------------------------------------------------------------

### Situación actual 

```{r}

Saber2020 <- UnalData::SaberPro %>% filter(YEAR == 2020) 

col <- c("#29ABE2", 
         "#8CC63F") 

Msj <- "Gráfico de radar para representar los puntajes multivariados de la prueba Saber Pro."

Plot_Radar(datos       = Saber2020,
           categoria   = SEXO,
           variables   = vars(PUNTAJE_GLOBAL, PUNT_RAZO_CUANT, PUNT_INGLES,
                              PUNT_LECT_CRIT, PUNT_COMP_CIUD, PUNT_COMU_ESCR),
          # estadistico = "SD",
           colores     = pals::jet(2),
           rango       = c(0, NaN),
           titulo      = "SPIDER PLOT",
           libreria    = "plotly",
           estilo      = list(ply.LegendTitle = "SEDE:", ply.LegendPosition = list(x = 0.15, y = -0.15, orientation = "h"),
                              ply.Relleno = "tonext", ply.Opacidad = 0.5, ply.Credits = list(x = 0.7, y = -0.1, text = Msj)
                              )
           )
```

### Tabla

```{r}
SaberT <- UnalData::SaberPro %>% relocate(PUNT_RAZO_CUANT, PUNT_LECT_CRIT, PUNT_COMP_CIUD, PUNT_INGLES, PUNT_COMU_ESCR, PUNTAJE_GLOBAL) %>%
         pivot_longer(starts_with("PUNT"),
                      names_to = "Prueba",
                      values_to = "Puntaje") %>%
         mutate(Prueba = case_when(Prueba == "PUNTAJE_GLOBAL" ~ "Global",
                                   Prueba == "PUNT_COMP_CIUD" ~ "Competencias Ciudadanas",
                                   Prueba == "PUNT_COMU_ESCR" ~ "Comunicación Escrita",
                                   Prueba == "PUNT_INGLES" ~ "Inglés",
                                   Prueba == "PUNT_LECT_CRIT" ~ "Lectura Crítica",
                                   Prueba == "PUNT_RAZO_CUANT" ~ "Razonamiento Cuantitativo"),
                Variable = "sexo") %>%
        group_by(Variable, YEAR, SEXO, Prueba) %>%
        summarise(Total = round(mean(Puntaje, na.rm = TRUE), 2),
                  desv = round(sd(Puntaje, na.rm = TRUE), 2),
                  n = n(), .groups = "drop") %>%
        rename(Clase = SEXO, Componente = Prueba) %>%
        arrange(YEAR, Clase, match(Componente, c("Razonamiento Cuantitativo",
                                                 "Comunicación Escrita",
                                                 "Lectura Crítica",
                                                 "Inglés",
                                                 "Competencias Ciudadanas",
                                                 "Global")))
Tabla.SaberPro(datos      = SaberT,
               variable   =  "SEXO",
               encabezado = "Puntajes promedio pruebas genéricas Saber Pro",
               leyenda    = Msj,
               colorHead  = "#99d8c9")
```

Edad
=======================================================================

Row
-----------------------------------------------------------------------

### Serie

```{r}
Saber <- UnalData::SaberPro %>%
  select(YEAR, CAT_EDAD, PUNTAJE_GLOBAL, PUNT_RAZO_CUANT, PUNT_INGLES, PUNT_LECT_CRIT, PUNT_COMP_CIUD, PUNT_COMU_ESCR) %>% 
mutate(CAT_EDAD = ifelse(CAT_EDAD == "26 o  más años", "26 o más años", CAT_EDAD)) 

Msj <- "Nota: <i>no se incluyen datos atípicos</i>"
Plot_Boxplot(datos       = Saber,
             variable    = PUNTAJE_GLOBAL,
             grupo1      = YEAR,
             grupo2      = CAT_EDAD,
             outliers    = FALSE,
             jitter      = "QUE",
             violin      = 12345,
             ylim        = c(0, 300),
             colores     = pals::jet(3),
             sizeOutlier = 1,
             colOutlier  = "#FF3366",
             textBox     = "Score",
             titulo      = "Evolución Puntaje Promedio Pruebas Genéricas Examen Saber Pro por grupos de edad",
             labelY      = "Puntaje",
             libreria    = "highcharter",
             estilo      = list(hc.Tema = 1, hc.Credits = Msj)
             )
```

Column
-----------------------------------------------------------------------

### Situación Actual

```{r}
Saber2020 <- UnalData::SaberPro %>% filter(YEAR == 2020) 

col <- c("#29ABE2", 
         "#8CC63F") 

Msj <- "Gráfico de radar para representar los puntajes multivariados de la prueba Saber Pro."

Plot_Radar(datos       = Saber2020,
           categoria   = CAT_EDAD,
           variables   = vars(PUNTAJE_GLOBAL, PUNT_RAZO_CUANT, PUNT_INGLES,
                              PUNT_LECT_CRIT, PUNT_COMP_CIUD, PUNT_COMU_ESCR),
          # estadistico = "SD",
           colores     = pals::jet(3),
           rango       = c(0, NaN),
           titulo      = "SPIDER PLOT",
           libreria    = "plotly",
           estilo      = list(ply.LegendTitle = "SEDE:", ply.LegendPosition = list(x = 0.15, y = -0.15, orientation = "h"),
                              ply.Relleno = "tonext", ply.Opacidad = 0.5, ply.Credits = list(x = 0.7, y = -0.1, text = Msj)
                              )
           )
```

### Tabla

```{r}
SaberT <- UnalData::SaberPro %>% relocate(PUNT_RAZO_CUANT, PUNT_LECT_CRIT, PUNT_COMP_CIUD, PUNT_INGLES, PUNT_COMU_ESCR, PUNTAJE_GLOBAL) %>%
         pivot_longer(starts_with("PUNT"),
                      names_to = "Prueba",
                      values_to = "Puntaje") %>%
         mutate(Prueba = case_when(Prueba == "PUNTAJE_GLOBAL" ~ "Global",
                                   Prueba == "PUNT_COMP_CIUD" ~ "Competencias Ciudadanas",
                                   Prueba == "PUNT_COMU_ESCR" ~ "Comunicación Escrita",
                                   Prueba == "PUNT_INGLES" ~ "Inglés",
                                   Prueba == "PUNT_LECT_CRIT" ~ "Lectura Crítica",
                                   Prueba == "PUNT_RAZO_CUANT" ~ "Razonamiento Cuantitativo"),
                Variable = "edad") %>%
        group_by(Variable, YEAR, CAT_EDAD, Prueba) %>%
        summarise(Total = round(mean(Puntaje, na.rm = TRUE), 2),
                  desv = round(sd(Puntaje, na.rm = TRUE), 2),
                  n = n(), .groups = "drop") %>%
        rename(Clase = CAT_EDAD, Componente = Prueba) %>%
        arrange(YEAR, Clase, match(Componente, c("Razonamiento Cuantitativo",
                                                 "Comunicación Escrita",
                                                 "Lectura Crítica",
                                                 "Inglés",
                                                 "Competencias Ciudadanas",
                                                 "Global")))
Tabla.SaberPro(datos      = SaberT,
               variable   =  "EDAD",
               encabezado = "Puntajes promedio pruebas genéricas Saber Pro",
               leyenda    = Msj,
               colorHead  = "#99d8c9")
```

Lugar de Nacimiento
=======================================================================

Row
-----------------------------------------------------------------------

### Total por departamentos y municipios

```{r}
SaberMap2020 <- UnalData::SaberPro %>% filter(YEAR == 2020)

Plot.Mapa(depto = SaberMap2020$COD_DEP_NAC, 
          mpio = SaberMap2020$COD_CIU_NAC,
          estadistico = "Promedio",
          variable = SaberMap2020$PUNTAJE_GLOBAL,
          tipo = "DeptoMpio",
          titulo = "Global.SaberPro 2020",
          naTo0 = FALSE,
          centroideMapa = "CUNDINAMARCA",
          zoomMapa = 6,
          cortes  = list(Deptos = c(0, 155, 170, 180, 185, Inf),
                         Mpios  = c(0, 155, 170, 180, 185, Inf)),
          colores = list(Deptos = c("#6812F2", "#5769F6", "#F6ED0D", "#EE6115", "#EC2525"),
                         Mpios  = pals::brewer.greens(5)),
          showSedes = TRUE)
```